<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Paperless.BatchProcessor-becdd68f-7171-4edb-a0bf-a3e98d1f00b6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.12" />
  </ItemGroup>
</Project>
