services:
  paperless-postgres:
    image: postgres:17.5
    container_name: paperless-postgres
    environment:
      - POSTGRES_DB=paperless
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - postgres_password
    networks:
      - paperless-network
    restart: unless-stopped

  paperless-rabbitmq:
    image: rabbitmq:4.2.0-management
    container_name: paperless-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=paperless
    ports:
      - "5672:5672" # RabbitMQ main port (AMQP protocol)
      - "15672:15672" # Management console
    volumes:
      - ./config/myrabbitmq.conf:/etc/rabbitmq/rabbitmq.conf # Custom configuration file, .conf for new style format
    networks:
      - paperless-network
    restart: unless-stopped

  paperless-backend:
    build:
      context: ./paperless/src/paperless
      dockerfile: Dockerfile
    container_name: paperless-backend
    volumes:
      - ./logs:/app/logs
    ports:
      - "5001:5001"
      - "7081:7081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001 # http://+:7081 would require certificate for docker container
      - POSTGRES_HOST=paperless-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=paperless
      - POSTGRES_USERNAME=paperless
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_INPUTQUEUE=${RABBITMQ_INPUTQUEUE}
      - RABBITMQ_RESULTQUEUE=${RABBITMQ_RESULTSQUEUE}

    depends_on:
      - paperless-postgres
      - paperless-rabbitmq
    secrets:
      - postgres_password
    networks:
      - paperless-network
    restart: unless-stopped

  paperless-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: paperless-frontend
    ports:
      - "80:80"
    depends_on:
      - paperless-backend
    networks:
      - paperless-network
    restart: unless-stopped
    
  paperless-ocrworker:
    build:
      context: ./paperless/src/Paperless.OcrWorker
      dockerfile: Dockerfile
    container_name: paperless-ocrworker
    depends_on:
      - paperless-rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_INPUTQUEUE=${RABBITMQ_INPUTQUEUE}
    networks:
      - paperless-network

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  rabbit_password:
    file: ./secrets/rabbit_password.txt
  minio_password:
    file: ./secrets/minio_password.txt

networks:
  paperless-network:
    driver: bridge

volumes:
  postgres_data: