<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Paperless.OcrWorker-50a3b16d-f3dc-4c00-b6f3-694143a46cd7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
    <PackageReference Include="Minio" Version="7.0.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
  </ItemGroup>
	<ItemGroup>
		<None Include="log4net.config" CopyToOutputDirectory="Always" />
	</ItemGroup>
</Project>
